{
 "title": "kong websocket",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "websocket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myapp_kong_websocket_server_connections_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Disconnection",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myapp_kong_websocket_connection_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "myapp_kong_websocket_server_active_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "websocket connection duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "myapp_kong_websocket_connection_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handshake Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "myapp_kong_websocket_connection_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "websocket bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "received message size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "myapp_kong_websocket_server_received_message_size_bytes_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sent message size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "myapp_kong_websocket_server_sent_message_size_bytes_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}